# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
# WARNING: Be careful in setting values for default because these values
# are being used in production as well. Be sure to override the values in production
# if you're not intending to use it there
  aws_access_id: AKIAJ7AMISQS7OO5GF5A
  aws_access_secret: 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
  aws_bucket: 'am2staging'
  aws_region: 'ap-southeast-2'
  aws_transcoder_region: 'us-west-1'
  aws_transcoder_media_pipeline: '1450163869399-xviy6q'

development:
  <<: *default
  secret_key_base: f156181de0a73c2d9cc16331a46a1d6de0d8c8d9a7f555e714726249b4f0ebfc16e91c56925b351c6e0d3019ef1f1a28bd10a5ad228387e8f29d624493f44c2d

test:
  <<: *default
  secret_key_base: 3e16cff009a4674d237b32c39ed8f137555f76c8abc355cdcad222b73d4036b83780f615e5e420fb54fa30da701fb0fabdcb5b369598221bb56af76980e3c5b7

staging:
  <<: *default
  aws_access_id: <%= ENV["AWS_ACCESS_ID"] %>
  aws_access_secret: <%= ENV["AWS_ACCESS_SECRET"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_transcoder_region: <%= ENV["AWS_TRANSCODER_REGION"] %>
  aws_transcoder_media_pipeline: <%= ENV["AWS_MEDIA_PIPELINE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  aws_access_id: <%= ENV["AWS_ACCESS_ID"] %>
  aws_access_secret: <%= ENV["AWS_ACCESS_SECRET"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_transcoder_region: <%= ENV["AWS_TRANSCODER_REGION"] %>
  aws_transcoder_media_pipeline: <%= ENV["AWS_MEDIA_PIPELINE"] %>
